fullnameOverride: ""
nameOverride: ""
namespaceOverride: ""

replicaCount: 1

image:
  repository: kaasops/ingress2gateway
  tag: "" # rewrites Chart.AppVersion
  pullPolicy: IfNotPresent

# -- enables CRD creation and management.
# -- with this option, if you remove this chart, all crd resources will be deleted with it.
createCRD: true

strategy: {}
# rollingUpdate:
#  maxSurge: 25%
#  maxUnavailable: 25%
# type: RollingUpdate

imagePullSecrets: []

nodeSelector: {}

securityContext: {}
  # allowPrivilegeEscalation: false
  # runAsGroup: 1000
  # runAsNonRoot: true
  # readOnlyRootFilesystem: true
  # seccompProfile:
  #   type: RuntimeDefault
  # capabilities:
  #   drop:
  #     - ALL

podSecurityContext: {}

tolerations: {}

resources:
  limits:
    cpu: "500m"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 50Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  create: true
  annotations: {}
  extraLabels: {}

# extra Labels for Pods, Deployment
extraLabels: {}

# Annotations to be added to the deployment
annotations: {}

# Args to path to operator
# args:

# gateway: default

# comma separated list of providers
providers: ingress-nginx
